name: Test and build mohist 1.12.2

on:
  push:
    branches: [ 1.12.2 ]
  pull_request:
    branches: [ 1.12.2 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup mohist 1.12.2
      run: |
        chmod +x ./gradlew
        ./gradlew setup
        ./gradlew setup installerJar
    - name: ls
      run: |
        find . -name '*.jar' | xargs ls -l
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: mohist
        path: projects/mohist/build/libs/mohist-*.jar
